// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to projects lives here.
// Nested objects (categories, projectStatuses, linkTypes) are merged shallowly, so they exist in BOTH languages.
const arErrors = (n) => (n === 1 ? 'خطأ واحد' : n === 2 ? 'خطآن' : n <= 10 ? `${n} أخطاء` : `${n} خطأً`)

export default {
  ar: {
    title: 'المشاريع',
    description: 'أعمال معرض المشاريع في الموقع: الغلاف والصور والفريق والروابط لكل مشروع.',
    new: 'مشروع جديد',
    createTitle: 'إضافة مشروع',
    editTitle: 'تعديل المشروع',
    notFoundTitle: 'المشروع غير موجود',

    // list
    searchPlaceholder: 'ابحث بالاسم أو العميل أو الرابط المختصر…',
    colProject: 'المشروع',
    colCategory: 'التصنيف',
    colClient: 'العميل',
    colYear: 'السنة',
    colFeatured: 'مميّز',
    colTeam: 'الفريق',
    colLinks: 'الروابط',
    categoryFilter: 'التصنيف',
    featuredFilter: 'التمييز',
    featuredOnly: 'المميّزة فقط',
    notFeatured: 'غير المميّزة',
    featuredToggle: (name) => `مميّز: ${name}`,
    teamCount: (n) => `أعضاء الفريق: ${n}`,
    linksCount: (n) => `الروابط: ${n}`,
    deleteTitle: 'حذف المشروع',
    deleteMessage: (name) =>
      `هل تريد حذف المشروع «${name}»؟ سيتم أيضًا حذف فريقه وروابطه وجميع صوره (الغلاف والمعرض وصور الفريق) نهائيًا، ولا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا توجد مشاريع بعد',
    emptyHint: 'أضف أول مشروع ليظهر في معرض الأعمال.',
    reorderIntro: 'اسحب المشاريع لتغيير ترتيب ظهورها في الموقع. يُحفظ الترتيب تلقائيًا.',

    // lookups
    categories: { web: 'ويب', mobile: 'تطبيقات موبايل', ai: 'ذكاء اصطناعي', design: 'تصميم', erp: 'أنظمة ERP' },
    projectStatuses: { completed: 'مكتمل', in_progress: 'قيد التنفيذ' },
    linkTypes: {
      website: 'الموقع الإلكتروني',
      github: 'GitHub',
      behance: 'Behance',
      instagram: 'إنستغرام',
      facebook: 'فيسبوك',
      linkedin: 'لينكدإن',
      x: 'إكس (X)',
      whatsapp: 'واتساب',
      other: 'أخرى',
    },

    // form: tabs
    tabsLabel: 'أقسام المشروع',
    tabGeneral: 'عام',
    tabMedia: 'الوسائط',
    tabTeam: 'الفريق',
    tabLinks: 'الروابط',
    tabErrors: arErrors,
    unsavedOnNested: 'لديك تغييرات غير محفوظة في قسمي «عام» و«الوسائط». عد إلى أحدهما واضغط «حفظ» قبل مغادرة الصفحة.',
    saveFirstTitle: 'احفظ المشروع أولًا',
    saveFirstTeam: 'يمكنك إضافة أعضاء الفريق بعد حفظ بيانات المشروع الأساسية. بعد الحفظ ننقلك إلى هذا القسم مباشرة.',
    saveFirstLinks: 'يمكنك إضافة الروابط بعد حفظ بيانات المشروع الأساسية. بعد الحفظ ننقلك إلى قسم الفريق، ويمكنك الانتقال منه إلى الروابط بنقرة واحدة.',
    saveAndContinue: 'حفظ ومتابعة',

    // form: general
    basicInfo: 'المعلومات الأساسية',
    slug: 'الرابط المختصر (slug)',
    slugHintCreate: 'اتركه فارغًا ليُولَّد تلقائيًا من الاسم الإنجليزي. أحرف إنجليزية صغيرة وأرقام وشرطات فقط.',
    slugHintEdit: 'اتركه فارغًا للإبقاء على الرابط الحالي. تغييره يغيّر عنوان صفحة المشروع في الموقع.',
    slugInvalid: 'استخدم أحرفًا إنجليزية صغيرة وأرقامًا وشرطات فقط (مثال: acme-portal).',
    category: 'التصنيف',
    categoryPlaceholder: 'اختر التصنيف',
    client: 'العميل',
    year: 'السنة',
    featured: 'مشروع مميّز',
    featuredHint: 'تظهر المشاريع المميّزة في قسم «مشاريع مختارة» في الصفحة الرئيسية.',
    name: 'اسم المشروع',
    short: 'وصف مختصر',
    shortHint: 'سطر واحد يظهر في بطاقة المشروع.',
    descriptionField: 'الوصف الكامل',

    // form: media
    cover: 'صورة الغلاف',
    coverHint: 'تظهر في بطاقة المشروع وفي أعلى صفحته.',
    gallery: 'معرض الصور',
    galleryHint: 'حتى 50 صورة. اسحب الصور لإعادة ترتيبها.',
    galleryMax: 'الحد الأقصى 50 صورة.',
    video: 'رابط الفيديو',
    videoHint: 'اختياري. روابط YouTube وVimeo تُعرض كمشغّل داخل صفحة المشروع، وأي رابط آخر يظهر كزر «مشاهدة الفيديو».',
    videoPlaceholder: 'https://www.youtube.com/watch?v=…',

    // team
    teamTitle: 'أعضاء الفريق',
    teamDescription: 'من عمل على هذا المشروع. يُحفظ كل تغيير في هذا القسم مباشرة دون الحاجة إلى زر «حفظ».',
    addMember: 'إضافة عضو',
    memberNew: 'إضافة عضو فريق',
    memberEdit: 'تعديل عضو الفريق',
    memberName: 'الاسم',
    memberRole: 'المسمى الوظيفي',
    memberTasks: 'المهام',
    memberTasksHint: 'اكتب المهمة ثم اضغط Enter لإضافتها.',
    memberAvatar: 'الصورة الشخصية',
    editMember: (name) => `تعديل: ${name}`,
    deleteMember: (name) => `حذف: ${name}`,
    tasksCount: (n) => (n === 1 ? 'مهمة واحدة' : n === 2 ? 'مهمتان' : n <= 10 ? `${n} مهام` : `${n} مهمة`),
    deleteMemberTitle: 'حذف عضو الفريق',
    deleteMemberMessage: (name) => `هل تريد حذف «${name}» من فريق المشروع؟ تُحذف صورته أيضًا.`,
    noMembers: 'لا يوجد أعضاء في الفريق بعد',
    noMembersHint: 'استخدم زر «إضافة عضو» لإضافة أول عضو يظهر في صفحة المشروع.',

    // links
    linksTitle: 'روابط المشروع',
    linksDescription: 'روابط خارجية تظهر في صفحة المشروع (الموقع، GitHub، وسائل التواصل…). يُحفظ كل تغيير مباشرة.',
    addLink: 'إضافة رابط',
    linkNew: 'إضافة رابط',
    linkEdit: 'تعديل الرابط',
    linkType: 'النوع',
    linkUrl: 'الرابط',
    editLink: (url) => `تعديل: ${url}`,
    deleteLink: (url) => `حذف: ${url}`,
    deleteLinkTitle: 'حذف الرابط',
    deleteLinkMessage: (url) => `هل تريد حذف الرابط «${url}»؟`,
    noLinks: 'لا توجد روابط بعد',
    noLinksHint: 'استخدم زر «إضافة رابط» لإضافة أول رابط يظهر في صفحة المشروع.',
    openLink: 'فتح الرابط في تبويب جديد',
  },

  en: {
    title: 'Projects',
    description: 'The portfolio projects shown on the website: cover, images, team and links of every project.',
    new: 'New project',
    createTitle: 'Add a project',
    editTitle: 'Edit project',
    notFoundTitle: 'Project not found',

    searchPlaceholder: 'Search by name, client or slug…',
    colProject: 'Project',
    colCategory: 'Category',
    colClient: 'Client',
    colYear: 'Year',
    colFeatured: 'Featured',
    colTeam: 'Team',
    colLinks: 'Links',
    categoryFilter: 'Category',
    featuredFilter: 'Featured',
    featuredOnly: 'Featured only',
    notFeatured: 'Not featured',
    featuredToggle: (name) => `Featured: ${name}`,
    teamCount: (n) => `${n} team members`,
    linksCount: (n) => `${n} links`,
    deleteTitle: 'Delete project',
    deleteMessage: (name) =>
      `Delete the project “${name}”? Its team members, links and all of its images (cover, gallery and team photos) are deleted with it. This cannot be undone.`,
    emptyTitle: 'No projects yet',
    emptyHint: 'Add the first project so it shows in the portfolio.',
    reorderIntro: 'Drag the projects to change the order they appear in on the website. The order is saved automatically.',

    categories: { web: 'Web', mobile: 'Mobile', ai: 'AI', design: 'Design', erp: 'ERP' },
    projectStatuses: { completed: 'Completed', in_progress: 'In progress' },
    linkTypes: {
      website: 'Website',
      github: 'GitHub',
      behance: 'Behance',
      instagram: 'Instagram',
      facebook: 'Facebook',
      linkedin: 'LinkedIn',
      x: 'X',
      whatsapp: 'WhatsApp',
      other: 'Other',
    },

    tabsLabel: 'Project sections',
    tabGeneral: 'General',
    tabMedia: 'Media',
    tabTeam: 'Team',
    tabLinks: 'Links',
    tabErrors: (n) => (n === 1 ? '1 error' : `${n} errors`),
    unsavedOnNested: 'You have unsaved changes in General or Media. Go back to one of them and press Save before leaving the page.',
    saveFirstTitle: 'Save the project first',
    saveFirstTeam: 'Team members can be added once the basic project details are saved. After saving you land straight on this section.',
    saveFirstLinks: 'Links can be added once the basic project details are saved. After saving you land on the Team section, and Links is one click away.',
    saveAndContinue: 'Save and continue',

    basicInfo: 'Basic information',
    slug: 'Slug',
    slugHintCreate: 'Leave blank to generate it from the English name. Lowercase letters, numbers and hyphens only.',
    slugHintEdit: 'Leave blank to keep the current one. Changing it changes the address of the project page on the website.',
    slugInvalid: 'Use lowercase letters, numbers and hyphens only (for example acme-portal).',
    category: 'Category',
    categoryPlaceholder: 'Choose a category',
    client: 'Client',
    year: 'Year',
    featured: 'Featured project',
    featuredHint: 'Featured projects appear in the “Selected projects” section on the home page.',
    name: 'Project name',
    short: 'Short description',
    shortHint: 'One line shown on the project card.',
    descriptionField: 'Full description',

    cover: 'Cover image',
    coverHint: 'Shown on the project card and at the top of its page.',
    gallery: 'Image gallery',
    galleryHint: 'Up to 50 images. Drag the images to reorder them.',
    galleryMax: 'At most 50 images.',
    video: 'Video link',
    videoHint: 'Optional. YouTube and Vimeo links play inside the project page; any other link shows a “Watch video” button.',
    videoPlaceholder: 'https://www.youtube.com/watch?v=…',

    teamTitle: 'Team members',
    teamDescription: 'The people who worked on this project. Every change in this section is saved immediately — no Save button needed.',
    addMember: 'Add member',
    memberNew: 'Add a team member',
    memberEdit: 'Edit team member',
    memberName: 'Name',
    memberRole: 'Role',
    memberTasks: 'Tasks',
    memberTasksHint: 'Type a task and press Enter to add it.',
    memberAvatar: 'Photo',
    editMember: (name) => `Edit: ${name}`,
    deleteMember: (name) => `Delete: ${name}`,
    tasksCount: (n) => (n === 1 ? '1 task' : `${n} tasks`),
    deleteMemberTitle: 'Delete team member',
    deleteMemberMessage: (name) => `Remove “${name}” from the project team? Their photo is deleted too.`,
    noMembers: 'No team members yet',
    noMembersHint: 'Use the “Add member” button to add the first person shown on the project page.',

    linksTitle: 'Project links',
    linksDescription: 'External links shown on the project page (website, GitHub, social media…). Every change is saved immediately.',
    addLink: 'Add link',
    linkNew: 'Add a link',
    linkEdit: 'Edit link',
    linkType: 'Type',
    linkUrl: 'URL',
    editLink: (url) => `Edit: ${url}`,
    deleteLink: (url) => `Delete: ${url}`,
    deleteLinkTitle: 'Delete link',
    deleteLinkMessage: (url) => `Delete the link “${url}”?`,
    noLinks: 'No links yet',
    noLinksHint: 'Use the “Add link” button to add the first link shown on the project page.',
    openLink: 'Open the link in a new tab',
  },
}
