// Strings of the app shell (login page, layout, errors). Feature strings live in features/<area>/strings.js.
export default {
  ar: {
    loginTitle: 'تسجيل الدخول',
    loginSubtitle: 'ادخل إلى لوحة تحكم NGP TechWorld لإدارة محتوى الموقع.',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    showPassword: 'إظهار كلمة المرور',
    hidePassword: 'إخفاء كلمة المرور',
    signIn: 'دخول',
    signingIn: 'جارٍ الدخول…',
    signOut: 'تسجيل الخروج',
    account: 'حسابي',
    accountMenu: 'قائمة الحساب',
    signedInAs: 'مسجّل الدخول باسم',
    notAdmin: 'هذا الحساب لا يملك صلاحية الدخول إلى لوحة التحكم.',
    tooManyAttempts: (seconds) => (seconds ? `محاولات كثيرة. حاول مرة أخرى بعد ${seconds} ثانية.` : 'محاولات كثيرة. حاول مرة أخرى بعد قليل.'),
    invalidCredentials: 'بيانات الدخول غير صحيحة.',
    emailRequired: 'أدخل بريدك الإلكتروني',
    passwordRequired: 'أدخل كلمة المرور',
    loginFooter: 'لوحة التحكم مخصصة لفريق NGP TechWorld فقط.',
    checkingSession: 'جارٍ التحقق من الجلسة…',
    serverUnreachable: 'تعذّر الاتصال بالخادم',
    serverUnreachableHint: 'تأكد من تشغيل الخادم واتصالك بالإنترنت ثم أعد المحاولة.',
    brandTagline: 'لوحة التحكم',
  },
  en: {
    loginTitle: 'Sign in',
    loginSubtitle: 'Access the NGP TechWorld dashboard to manage the website content.',
    email: 'Email',
    password: 'Password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    signOut: 'Sign out',
    account: 'My account',
    accountMenu: 'Account menu',
    signedInAs: 'Signed in as',
    notAdmin: 'This account is not allowed to use the dashboard.',
    tooManyAttempts: (seconds) => (seconds ? `Too many attempts. Try again in ${seconds} seconds.` : 'Too many attempts. Try again shortly.'),
    invalidCredentials: 'The credentials are incorrect.',
    emailRequired: 'Enter your email',
    passwordRequired: 'Enter your password',
    loginFooter: 'The dashboard is for the NGP TechWorld team only.',
    checkingSession: 'Checking your session…',
    serverUnreachable: 'Cannot reach the server',
    serverUnreachableHint: 'Make sure the server is running and you are online, then try again.',
    brandTagline: 'Dashboard',
  },
}
