// Feature strings: { ar: {…}, en: {…} }. Save / Cancel / validation messages come from `useCommon()`.
export default {
  ar: {
    sectionLaunch: 'صفحة الافتتاح',
    sectionVisitors: 'عدّاد الزوّار',
    visitorsHint: 'رقم صغير في أسفل الموقع. التسجيل شغّال دائماً حتى لو المفتاح مطفأ، فالرقم حقيقي لحظة ما تُظهره.',
    visitorsEnabled: 'إظهار العدّاد في الفوتر',
    visitorsEnabledHint: 'مطفأ الآن. أظهره لمّا يصير الرقم يستاهل.',
    visitorsSoFar: (n) => `المسجَّل حتى اللحظة: ${n}`,
    launchHint: 'تعرض عدّاً تنازلياً بدل الموقع لحتى موعد الافتتاح. الداشبورد والـ API يظلّان يعملان كالعادة.',
    launchEnabled: 'تفعيل العدّ التنازلي',
    launchEnabledHint: 'الزوّار يرون صفحة الافتتاح بدل الموقع.',
    launchAt: 'موعد الافتتاح',
    launchAtHint: 'بتوقيتك المحلي. الموقع يفتح من نفسه في هذه اللحظة دون الحاجة لإطفاء المفتاح.',
    launchLive: 'العدّ التنازلي يعمل الآن — الموقع مغلق أمام الزوّار.',
    launchPassed: 'الموعد مضى، والموقع مفتوح. يمكنك إطفاء المفتاح وحذف الموعد.',
    title: 'إعدادات الموقع',
    description: 'بيانات التواصل وروابط الشبكات الاجتماعية التي تظهر للزوار في الموقع.',

    contactTitle: 'بيانات التواصل',
    contactDescription: 'تظهر في تذييل الموقع وفي صفحة «اتصل بنا».',
    email: 'البريد الإلكتروني',
    emailHint: 'اتركه فارغًا لإخفائه من الموقع.',
    phone: 'رقم الهاتف',
    phoneHint: 'اكتبه بالصيغة الدولية كما تريد أن يظهر. اتركه فارغًا لإخفائه من الموقع.',

    socialTitle: 'روابط الشبكات الاجتماعية',
    socialDescription: 'تظهر أزرار هذه الشبكات في صفحة «اتصل بنا».',
    socialInfo: 'الرابط الفارغ يُخفي زر تلك الشبكة من الموقع. أدخل الرابط كاملًا بدءًا من',
    networks: {
      facebook: { label: 'فيسبوك', hint: 'رابط صفحتك على فيسبوك، مثل' },
      instagram: { label: 'إنستغرام', hint: 'رابط حسابك على إنستغرام، مثل' },
      linkedin: { label: 'لينكد إن', hint: 'رابط صفحة الشركة على لينكد إن، مثل' },
      x: { label: 'إكس (تويتر)', hint: 'رابط حسابك على منصة إكس، مثل' },
      whatsapp: { label: 'واتساب', hint: 'رابط المحادثة المباشرة: رمز الدولة ثم الرقم دون + أو مسافات، مثل' },
    },

    sectionsTitle: 'أقسام الموقع',
    sectionsDescription: 'أوقف أي قسم لإخفائه من الموقع بالكامل دون حذف محتواه، وأعد تشغيله متى شئت.',
    sectionsPages: 'الصفحات',
    sectionsPagesHint: 'إيقاف صفحة يخفيها من كل مكان: تبويب القائمة، رابط التذييل، وقسمها في الصفحة الرئيسية. ومن يفتح رابطها مباشرة يرى صفحة «غير موجودة».',
    sectionsHome: 'أقسام الصفحة الرئيسية',
    sections: {
      services: 'الخدمات',
      portfolio: 'أعمالنا',
      team: 'فريقنا',
      about: 'من نحن',
      intro: 'الفقرة التعريفية',
      stats: 'الأرقام والإحصائيات',
      process: 'مراحل العمل',
      promo: 'الفيديو التعريفي',
      cta: 'دعوة للتواصل',
      testimonials: 'آراء العملاء',
      partners: 'شركاؤنا',
      faq: 'الأسئلة الشائعة',
    },
    sectionHints: {
      services: 'الصفحة والتبويب وقسم الخدمات في الرئيسية',
      portfolio: 'الصفحة وصفحات المشاريع والتبويب و«أعمال مختارة» وزر «شاهد أعمالنا»',
      team: 'الصفحة وصفحات الأعضاء والتبويب',
      about: 'الصفحة والتبويب',
    },

    discard: 'تجاهل التغييرات',
    loadFailedTitle: 'تعذّر تحميل الإعدادات',
  },
  en: {
    sectionLaunch: 'Launch page',
    sectionVisitors: 'Visit counter',
    visitorsHint: 'A small number at the foot of the site. Visits are recorded whether or not the switch is on, so the number is a real one the moment you show it.',
    visitorsEnabled: 'Show the counter in the footer',
    visitorsEnabledHint: 'Off for now. Turn it on once the number is worth showing.',
    visitorsSoFar: (n) => `Recorded so far: ${n}`,
    launchHint: 'Shows a countdown instead of the site until the launch moment. The dashboard and API keep working as usual.',
    launchEnabled: 'Run the countdown',
    launchEnabledHint: 'Visitors see the launch page instead of the site.',
    launchAt: 'Launch moment',
    launchAtHint: 'In your local time. The site opens by itself at that moment — nobody has to switch this off.',
    launchLive: 'The countdown is running — the site is closed to visitors.',
    launchPassed: 'The moment has passed and the site is open. You can switch this off and clear the date.',
    title: 'Site settings',
    description: 'The contact details and social links that visitors see on the website.',

    contactTitle: 'Contact details',
    contactDescription: 'Shown in the website footer and on the Contact page.',
    email: 'Email',
    emailHint: 'Leave empty to hide it from the website.',
    phone: 'Phone number',
    phoneHint: 'Write it in international format, exactly as it should appear. Leave empty to hide it from the website.',

    socialTitle: 'Social links',
    socialDescription: 'The buttons of these networks appear on the Contact page.',
    socialInfo: 'An empty link hides that network’s button on the website. Enter the full link, starting with',
    networks: {
      facebook: { label: 'Facebook', hint: 'Link to your Facebook page, e.g.' },
      instagram: { label: 'Instagram', hint: 'Link to your Instagram account, e.g.' },
      linkedin: { label: 'LinkedIn', hint: 'Link to the company page on LinkedIn, e.g.' },
      x: { label: 'X (Twitter)', hint: 'Link to your X account, e.g.' },
      whatsapp: { label: 'WhatsApp', hint: 'Direct chat link: the country code and number, no + or spaces, e.g.' },
    },

    sectionsTitle: 'Website sections',
    sectionsDescription: 'Switch a section off to hide it from the whole website without deleting its content; switch it back on any time.',
    sectionsPages: 'Pages',
    sectionsPagesHint: 'Switching a page off hides it everywhere: the menu tab, the footer link and its home-page section. Opening its address directly shows “Page not found”.',
    sectionsHome: 'Home page sections',
    sections: {
      services: 'Services',
      portfolio: 'Portfolio',
      team: 'Team',
      about: 'About',
      intro: 'Intro paragraph',
      stats: 'Stats',
      process: 'How we work',
      promo: 'Promo video',
      cta: 'Call to action',
      testimonials: 'Testimonials',
      partners: 'Partners',
      faq: 'FAQ',
    },
    sectionHints: {
      services: 'Page, menu tab and the services section on the home page',
      portfolio: 'Page, project pages, menu tab, “Featured work” and the “See our work” button',
      team: 'Page, member pages and menu tab',
      about: 'Page and menu tab',
    },

    discard: 'Discard changes',
    loadFailedTitle: 'Could not load the settings',
  },
}
