// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to this feature is here.
export default {
  ar: {
    title: 'الشركاء',
    description: 'الشركاء وشعاراتهم التي تظهر في الموقع.',
    new: 'شريك جديد',
    createTitle: 'إضافة شريك',
    editTitle: 'تعديل الشريك',
    notFoundTitle: 'الشريك غير موجود',
    searchPlaceholder: 'ابحث باسم الشريك…',
    partner: 'الشريك',
    name: 'الاسم',
    website: 'الموقع الإلكتروني',
    websiteHint: 'اختياري. عند إضافته يصبح شعار الشريك رابطًا إلى موقعه.',
    opensInNewTab: '(يفتح في نافذة جديدة)',
    logo: 'الشعار',
    logoHint: 'اختياري. يظهر في قسم الشركاء في الموقع، ويُفضَّل شعار بخلفية شفافة.',
    activeLabel: 'فعّال',
    activeHint: 'الشركاء غير الفعّالين لا يظهرون في الموقع.',
    deleteTitle: 'حذف الشريك',
    deleteMessage: (name) => `هل تريد حذف الشريك «${name}»؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا يوجد شركاء بعد',
    emptyHint: 'أضف أول شريك ليظهر شعاره في الموقع.',
    reorderIntro: 'اسحب الشركاء لتغيير ترتيب ظهورهم في الموقع. يُحفظ الترتيب تلقائيًا.',
  },
  en: {
    title: 'Partners',
    description: 'The partners and their logos shown on the website.',
    new: 'New partner',
    createTitle: 'Add a partner',
    editTitle: 'Edit partner',
    notFoundTitle: 'Partner not found',
    searchPlaceholder: 'Search by partner name…',
    partner: 'Partner',
    name: 'Name',
    website: 'Website',
    websiteHint: 'Optional. When set, the partner’s logo links to their website.',
    opensInNewTab: '(opens in a new tab)',
    logo: 'Logo',
    logoHint: 'Optional. Shown in the partners section of the website; a logo with a transparent background works best.',
    activeLabel: 'Active',
    activeHint: 'Inactive partners are not shown on the website.',
    deleteTitle: 'Delete partner',
    deleteMessage: (name) => `Delete the partner “${name}”? This cannot be undone.`,
    emptyTitle: 'No partners yet',
    emptyHint: 'Add the first partner so their logo shows on the website.',
    reorderIntro: 'Drag the partners to change the order they appear in on the website. The order is saved automatically.',
  },
}
