// Feature strings: { ar: {…}, en: {…} }. Generic words (save, cancel, delete, validation messages…) come from `useCommon()`.
export default {
  ar: {
    // list
    title: 'المستخدمون',
    description: 'أعضاء الفريق الذين يمكنهم الدخول إلى لوحة التحكم، وما يملك كل منهم صلاحية الوصول إليه.',
    new: 'مستخدم جديد',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    you: 'أنت',
    searchPlaceholder: 'ابحث بالاسم أو البريد الإلكتروني…',
    emptyTitle: 'لا يوجد مستخدمون',
    emptyHint: 'أضف عضوًا جديدًا ليتمكن من الدخول إلى لوحة التحكم.',
    deleteTitle: 'حذف المستخدم',
    deleteMessage: (name) => `هل تريد حذف المستخدم «${name}»؟ لن يتمكن من الدخول إلى لوحة التحكم بعد الآن.`,
    guardSelf: 'لا يمكنك حذف حسابك الخاص.',
    guardLastSuperAdmin: 'لا يمكن أن يبقى الموقع بلا مدير عام واحد على الأقل.',
    yourAccount: 'حسابك',
    yourAccountHint: 'غيّر اسمك أو بريدك الإلكتروني أو كلمة مرورك.',
    myAccount: 'حسابي',
    roleColumn: 'الدور',

    // create / edit
    createTitle: 'إضافة مستخدم',
    editTitle: 'تعديل المستخدم',
    notFoundTitle: 'المستخدم غير موجود',
    password: 'كلمة المرور',
    passwordHintCreate: 'ثمانية أحرف على الأقل.',
    passwordHintEdit: 'اتركها فارغة للإبقاء على كلمة المرور الحالية. تغييرها يُنهي جلسات هذا المستخدم على الأجهزة الأخرى.',
    showPassword: 'إظهار كلمة المرور',
    hidePassword: 'إخفاء كلمة المرور',

    // role & permissions
    roleLabel: 'الدور',
    roleSuperAdmin: 'مدير عام',
    roleSuperAdminHint: 'وصول كامل إلى كل الأقسام، وهو الوحيد القادر على إدارة المستخدمين.',
    roleAdmin: 'مدير محدود الصلاحيات',
    roleAdminHint: 'وصول إلى الأقسام التي تحددها أدناه فقط.',
    permissionsLabel: 'الأقسام المسموح بها',
    permissionsHint: 'اختر الأقسام التي يمكن لهذا المستخدم الوصول إليها وإدارتها.',
    permissionsRequired: 'اختر قسمًا واحدًا على الأقل',
    sections: {
      faqs: 'الأسئلة الشائعة',
      'page-content': 'محتوى الصفحات',
      partners: 'الشركاء',
      projects: 'المشاريع',
      requests: 'الطلبات',
      services: 'الخدمات',
      settings: 'إعدادات الموقع',
      stats: 'الإحصائيات',
      team: 'فريقنا',
      testimonials: 'آراء العملاء',
    },
  },
  en: {
    title: 'Users',
    description: 'The team members who can sign in to the dashboard, and what each of them can access.',
    new: 'New user',
    name: 'Name',
    email: 'Email',
    you: 'You',
    searchPlaceholder: 'Search name or email…',
    emptyTitle: 'No users',
    emptyHint: 'Add a team member so they can sign in to the dashboard.',
    deleteTitle: 'Delete user',
    deleteMessage: (name) => `Delete the user “${name}”? They will no longer be able to sign in to the dashboard.`,
    guardSelf: 'You cannot delete your own account.',
    guardLastSuperAdmin: 'The site cannot be left without at least one super admin.',
    yourAccount: 'Your account',
    yourAccountHint: 'Change your name, email or password.',
    myAccount: 'My account',
    roleColumn: 'Role',

    createTitle: 'Add a user',
    editTitle: 'Edit user',
    notFoundTitle: 'User not found',
    password: 'Password',
    passwordHintCreate: 'At least 8 characters.',
    passwordHintEdit: 'Leave empty to keep the current password. Changing it signs this user out of their other devices.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',

    roleLabel: 'Role',
    roleSuperAdmin: 'Super admin',
    roleSuperAdminHint: 'Full access to every section, and the only role that can manage users.',
    roleAdmin: 'Limited admin',
    roleAdminHint: 'Access only to the sections you pick below.',
    permissionsLabel: 'Allowed sections',
    permissionsHint: 'Choose the sections this user can access and manage.',
    permissionsRequired: 'Choose at least one section',
    sections: {
      faqs: 'FAQ',
      'page-content': 'Page content',
      partners: 'Partners',
      projects: 'Projects',
      requests: 'Requests',
      services: 'Services',
      settings: 'Site settings',
      stats: 'Stats',
      team: 'Our Team',
      testimonials: 'Testimonials',
    },
  },
}
