// Feature strings. Generic words (save, cancel, delete, "Active"…) come from `useCommon()`.
// `keyHints` (where a text appears on the public site) and `collections` are nested: both languages give every entry.
export default {
  ar: {
    title: 'محتوى الصفحات',
    description: 'عدّل النصوص والأقسام التي تظهر في الموقع: واجهة الصفحة الرئيسية، من نحن، خطوات العمل، القيم، الشريط الدعائي والتذييل.',
    infoTitle: 'قبل أن تبدأ',
    infoEmpty: 'عند ترك الحقل فارغًا يعرض الموقع نصّه الافتراضي المدمج فيه.',
    infoCache: 'تظهر التعديلات في الموقع خلال دقيقة تقريبًا، لأن المحتوى يُخزَّن مؤقتًا لمدة 60 ثانية.',

    tabsLabel: 'أقسام محتوى الصفحات',
    tabs: { home: 'الرئيسية', about: 'من نحن', pages: 'الصفحات', shared: 'الشريط والتذييل' },
    tabHints: {
      home: 'واجهة الصفحة الرئيسية وعناوين أقسامها وخطوات «كيف نعمل».',
      about: 'قصة الشركة والرؤية والرسالة والقيم وأسباب اختيارنا.',
      pages: 'عناوين ومقدّمات صفحات الخدمات ومعرض الأعمال والتواصل.',
      shared: 'عناصر تظهر في أكثر من صفحة: الشريط الدعائي والتذييل.',
    },
    // read after the tab name by screen readers, hence the leading comma
    tabEdited: (n) => `، تعديلات: ${n}`,

    emptyPlaceholder: 'فارغ — يعرض الموقع نصّه الافتراضي',
    edited: 'معدّل',
    revertItem: (label) => `إعادة «${label}» إلى القيمة المحفوظة`,
    charCount: (n, max) => `${n} / ${max}`,

    saveChanges: 'حفظ التعديلات',
    noUnsaved: 'لا توجد تعديلات غير محفوظة',
    unsaved: (n) => {
      if (n === 1) return 'تعديل واحد غير محفوظ'
      if (n === 2) return 'تعديلان غير محفوظان'
      if (n <= 10) return `${n} تعديلات غير محفوظة`
      return `${n} تعديلًا غير محفوظ`
    },
    discardAll: 'تجاهل التعديلات',
    discardTitle: 'تجاهل التعديلات؟',
    discardMessage: 'ستُفقد كل التعديلات غير المحفوظة في النصوص وتعود الحقول إلى قيمها المحفوظة.',
    discardConfirm: 'تجاهل',
    serverErrorTitle: 'رفض الخادم بعض القيم',

    hiddenOnSite: 'مخفي عن الموقع',
    allInactive: 'كل العناصر غير فعّالة، لذلك يعرض الموقع قائمته المدمجة.',
    titleLabel: 'العنوان',
    bodyLabel: 'الوصف',
    bodyHint: 'اختياري.',
    iconLabel: 'الأيقونة',
    iconHint: 'الأيقونة التي تظهر بجانب القيمة في الموقع.',
    iconNames: { quality: 'الجودة', innovation: 'الابتكار', commit: 'الالتزام', transparency: 'الشفافية' },
    activeLabel: 'ظاهر في الموقع',
    activeHint: 'العناصر غير الفعّالة لا تظهر في الموقع.',

    collections: {
      process_steps: {
        title: 'خطوات «كيف نعمل»',
        description: 'الخطوات المعروضة في قسم «كيف نعمل» بالصفحة الرئيسية.',
        add: 'إضافة خطوة',
        createTitle: 'إضافة خطوة',
        editTitle: 'تعديل الخطوة',
        emptyTitle: 'لا توجد خطوات بعد',
        emptyHint: 'يعرض الموقع حاليًا قائمة الخطوات المدمجة فيه. وعند إضافة خطوة سيعرض الموقع خطواتك أنت فقط، فأضف كل الخطوات التي تريدها.',
        deleteTitle: 'حذف الخطوة',
        deleteMessage: (name) => `هل تريد حذف الخطوة «${name}»؟ لا يمكن التراجع عن ذلك.`,
      },
      values: {
        title: 'القيم',
        description: 'القيم المعروضة في صفحة «من نحن». لكل قيمة عنوان وأيقونة.',
        add: 'إضافة قيمة',
        createTitle: 'إضافة قيمة',
        editTitle: 'تعديل القيمة',
        emptyTitle: 'لا توجد قيم بعد',
        emptyHint: 'يعرض الموقع حاليًا قائمة القيم المدمجة فيه. وعند إضافة قيمة سيعرض الموقع قيمك أنت فقط، فأضف كل القيم التي تريدها.',
        deleteTitle: 'حذف القيمة',
        deleteMessage: (name) => `هل تريد حذف القيمة «${name}»؟ لا يمكن التراجع عن ذلك.`,
      },
      why_us: {
        title: 'لماذا تختارنا؟',
        description: 'أسباب اختيار الشركة المعروضة في صفحة «من نحن».',
        add: 'إضافة سبب',
        createTitle: 'إضافة سبب',
        editTitle: 'تعديل السبب',
        emptyTitle: 'لا توجد أسباب بعد',
        emptyHint: 'يعرض الموقع حاليًا قائمة الأسباب المدمجة فيه. وعند إضافة سبب سيعرض الموقع أسبابك أنت فقط، فأضف كل الأسباب التي تريدها.',
        deleteTitle: 'حذف السبب',
        deleteMessage: (name) => `هل تريد حذف السبب «${name}»؟ لا يمكن التراجع عن ذلك.`,
      },
    },

    keyHints: {
      heroBadge: 'شارة صغيرة فوق العنوان الرئيسي في الصفحة الرئيسية.',
      heroT1: 'الجزء الأول من العنوان الرئيسي في الصفحة الرئيسية.',
      heroAccent: 'الجزء المميّز بلون مختلف في نهاية العنوان الرئيسي، ويأتي بعد الجزء الأول مباشرة.',
      heroSub: 'الفقرة تحت العنوان الرئيسي، وتظهر أيضًا وصفًا للصفحة في نتائج البحث.',
      heroCta1: 'الزر الرئيسي تحت العنوان، ويفتح صفحة التواصل.',
      heroCta2: 'الزر الثاني تحت العنوان، ويفتح معرض الأعمال.',
      intro: 'الفقرة التعريفية الكبيرة أسفل واجهة الصفحة الرئيسية مباشرة.',
      servicesKick: 'نص صغير فوق عنوان الخدمات في الصفحة الرئيسية وصفحة الخدمات.',
      servicesTitle: 'عنوان قسم الخدمات، وهو أيضًا عنوان صفحة الخدمات.',
      servicesAll: 'رابط أسفل الخدمات في الصفحة الرئيسية يفتح صفحة الخدمات.',
      featuredKick: 'نص صغير فوق عنوان المشاريع المختارة، ويُستخدم أيضًا في صفحة معرض الأعمال.',
      featuredTitle: 'عنوان قسم المشاريع المختارة في الصفحة الرئيسية.',
      processKick: 'نص صغير فوق عنوان «كيف نعمل».',
      processTitle: 'عنوان قسم «كيف نعمل».',
      processSub: 'الفقرة تحت عنوان «كيف نعمل». الخطوات نفسها تُعدَّل في القائمة أسفل هذا القسم.',
      testimonialsKick: 'نص صغير فوق عنوان آراء العملاء.',
      testimonialsTitle: 'عنوان قسم آراء العملاء.',
      partnersKick: 'نص صغير فوق عنوان الشركاء.',
      partnersTitle: 'عنوان قسم الشركاء.',
      faqKick: 'نص صغير فوق عنوان الأسئلة الشائعة.',
      faqTitle: 'عنوان قسم الأسئلة الشائعة.',
      ctaTitle: 'عنوان الشريط الذي يظهر قرب أسفل صفحات الموقع.',
      ctaSub: 'الفقرة تحت عنوان الشريط.',
      ctaBtn: 'زر الشريط، ويفتح صفحة التواصل.',
      servicesSub: 'الفقرة تحت عنوان صفحة الخدمات.',
      portfolioTitle: 'عنوان صفحة معرض الأعمال.',
      portfolioSub: 'الفقرة تحت عنوان صفحة معرض الأعمال.',
      contactTitle: 'عنوان صفحة التواصل.',
      contactSub: 'الفقرة تحت عنوان صفحة التواصل.',
      aboutTitle: 'عنوان صفحة «من نحن».',
      aboutStory: 'قصة الشركة تحت عنوان صفحة «من نحن».',
      visionT: 'عنوان بطاقة الرؤية في صفحة «من نحن».',
      vision: 'نص بطاقة الرؤية.',
      missionT: 'عنوان بطاقة الرسالة.',
      mission: 'نص بطاقة الرسالة.',
      valuesT: 'العنوان فوق قائمة القيم في صفحة «من نحن». القيم نفسها تُعدَّل في القائمة أسفل هذا القسم.',
      whyT: 'العنوان فوق قائمة «لماذا تختارنا» في صفحة «من نحن». الأسباب نفسها تُعدَّل في القائمة أسفل هذا القسم.',
      footTagline: 'وصف قصير في تذييل كل صفحة.',
      footRights: 'سطر حقوق النشر في أسفل كل صفحة.',
    },
  },

  en: {
    title: 'Page content',
    description: 'Edit the texts and sections shown on the website: the home hero, About, work steps, values, the banner and the footer.',
    infoTitle: 'Before you start',
    infoEmpty: 'Leave a field empty and the website keeps its own built-in text.',
    infoCache: 'Changes appear on the website within about a minute, because the content is cached for 60 seconds.',

    tabsLabel: 'Page content sections',
    tabs: { home: 'Home', about: 'About', pages: 'Pages', shared: 'Banner & footer' },
    tabHints: {
      home: 'The home page hero, its section headings and the “How we work” steps.',
      about: 'The company story, vision, mission, values and reasons to choose us.',
      pages: 'Headings and intros of the Services, Portfolio and Contact pages.',
      shared: 'Elements shown on more than one page: the call-to-action banner and the footer.',
    },
    tabEdited: (n) => `, ${n} edited`,

    emptyPlaceholder: 'Empty — the website shows its built-in text',
    edited: 'Edited',
    revertItem: (label) => `Revert “${label}” to saved`,
    charCount: (n, max) => `${n} / ${max}`,

    saveChanges: 'Save changes',
    noUnsaved: 'No unsaved changes',
    unsaved: (n) => (n === 1 ? '1 unsaved change' : `${n} unsaved changes`),
    discardAll: 'Discard changes',
    discardTitle: 'Discard changes?',
    discardMessage: 'All unsaved edits to the texts will be lost and the fields go back to their saved values.',
    discardConfirm: 'Discard',
    serverErrorTitle: 'The server rejected some values',

    hiddenOnSite: 'Hidden on the site',
    allInactive: 'Every item is inactive, so the website shows its built-in list.',
    titleLabel: 'Title',
    bodyLabel: 'Description',
    bodyHint: 'Optional.',
    iconLabel: 'Icon',
    iconHint: 'The icon shown next to the value on the website.',
    iconNames: { quality: 'Quality', innovation: 'Innovation', commit: 'Commitment', transparency: 'Transparency' },
    activeLabel: 'Shown on the site',
    activeHint: 'Inactive items are not shown on the website.',

    collections: {
      process_steps: {
        title: 'How we work — steps',
        description: 'The steps shown in the “How we work” section of the home page.',
        add: 'Add step',
        createTitle: 'Add a step',
        editTitle: 'Edit step',
        emptyTitle: 'No steps yet',
        emptyHint: 'The website is showing its built-in list of steps. Once you add a step it shows only your steps, so add every step you want.',
        deleteTitle: 'Delete step',
        deleteMessage: (name) => `Delete the step “${name}”? This cannot be undone.`,
      },
      values: {
        title: 'Values',
        description: 'The values shown on the About page. Each value has a title and an icon.',
        add: 'Add value',
        createTitle: 'Add a value',
        editTitle: 'Edit value',
        emptyTitle: 'No values yet',
        emptyHint: 'The website is showing its built-in list of values. Once you add a value it shows only your values, so add every value you want.',
        deleteTitle: 'Delete value',
        deleteMessage: (name) => `Delete the value “${name}”? This cannot be undone.`,
      },
      why_us: {
        title: 'Why choose us',
        description: 'The reasons to choose the company, shown on the About page.',
        add: 'Add reason',
        createTitle: 'Add a reason',
        editTitle: 'Edit reason',
        emptyTitle: 'No reasons yet',
        emptyHint: 'The website is showing its built-in list of reasons. Once you add a reason it shows only your reasons, so add every reason you want.',
        deleteTitle: 'Delete reason',
        deleteMessage: (name) => `Delete the reason “${name}”? This cannot be undone.`,
      },
    },

    keyHints: {
      heroBadge: 'Small badge above the main headline on the home page.',
      heroT1: 'First part of the main headline on the home page.',
      heroAccent: 'The highlighted (coloured) end of the main headline, right after the first part.',
      heroSub: 'Paragraph under the main headline. Also the page description shown in search results.',
      heroCta1: 'Main button under the headline. Opens the contact page.',
      heroCta2: 'Second button under the headline. Opens the portfolio.',
      intro: 'Large introduction paragraph right below the hero on the home page.',
      servicesKick: 'Small text above the services title on the home page and the Services page.',
      servicesTitle: 'Title of the services section. Also the title of the Services page.',
      servicesAll: 'Link under the services on the home page that opens the Services page.',
      featuredKick: 'Small text above the featured projects title. Also used on the Portfolio page.',
      featuredTitle: 'Title of the featured projects section on the home page.',
      processKick: 'Small text above the “How we work” title.',
      processTitle: 'Title of the “How we work” section.',
      processSub: 'Paragraph under the “How we work” title. The steps themselves are edited in the list below this section.',
      testimonialsKick: 'Small text above the testimonials title.',
      testimonialsTitle: 'Title of the testimonials section.',
      partnersKick: 'Small text above the partners title.',
      partnersTitle: 'Title of the partners section.',
      faqKick: 'Small text above the FAQ title.',
      faqTitle: 'Title of the FAQ section.',
      ctaTitle: 'Headline of the banner shown near the bottom of the site pages.',
      ctaSub: 'Paragraph under the banner headline.',
      ctaBtn: 'Banner button. Opens the contact page.',
      servicesSub: 'Paragraph under the title of the Services page.',
      portfolioTitle: 'Title of the Portfolio page.',
      portfolioSub: 'Paragraph under the title of the Portfolio page.',
      contactTitle: 'Title of the Contact page.',
      contactSub: 'Paragraph under the title of the Contact page.',
      aboutTitle: 'Title of the About page.',
      aboutStory: 'The company story shown under the title of the About page.',
      visionT: 'Title of the vision card on the About page.',
      vision: 'Text of the vision card.',
      missionT: 'Title of the mission card.',
      mission: 'Text of the mission card.',
      valuesT: 'Heading above the values list on the About page. The values themselves are edited in the list below this section.',
      whyT: 'Heading above the “Why choose us” list on the About page. The reasons themselves are edited in the list below this section.',
      footTagline: 'Short description in the footer of every page.',
      footRights: 'Copyright line at the very bottom of every page.',
    },
  },
}
