// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to this feature is here.
export default {
  ar: {
    title: 'الخدمات',
    description: 'الخدمات التي تعرضها الشركة في الموقع، لكل خدمة أيقونة ووصف وقائمة مزايا.',
    new: 'خدمة جديدة',
    createTitle: 'إضافة خدمة',
    editTitle: 'تعديل الخدمة',
    notFoundTitle: 'الخدمة غير موجودة',
    searchPlaceholder: 'ابحث في عناوين الخدمات…',
    service: 'الخدمة',
    features: 'المزايا',
    icon: 'الأيقونة',
    iconHint: 'تظهر بجانب الخدمة في الموقع.',
    serviceTitle: 'العنوان',
    serviceDescription: 'الوصف',
    featuresHint: 'نقاط قصيرة تظهر تحت وصف الخدمة. اكتب الميزة ثم اضغط Enter. يمكنك ترك القائمتين فارغتين.',
    deleteTitle: 'حذف الخدمة',
    deleteMessage: (name) => `هل تريد حذف الخدمة «${name}»؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا توجد خدمات بعد',
    emptyHint: 'أضف أول خدمة لتظهر في الموقع.',
    activeLabel: 'ظاهرة في الموقع',
    activeHint: 'الخدمة المخفية لا تظهر في الموقع ولا في قائمة الخدمات في نموذج التواصل.',
    reorderIntro: 'اسحب الخدمات لتغيير ترتيب ظهورها في الموقع. يُحفظ الترتيب تلقائيًا.',
    icons: {
      web: 'مواقع الويب',
      mobile: 'تطبيقات الجوال',
      design: 'التصميم',
      erp: 'أنظمة ERP',
      cloud: 'الحوسبة السحابية',
      ai: 'الذكاء الاصطناعي',
      support: 'الدعم الفني',
    },
  },
  en: {
    title: 'Services',
    description: 'The services the company shows on the website — each with an icon, a description and a list of features.',
    new: 'New service',
    createTitle: 'Add a service',
    editTitle: 'Edit service',
    notFoundTitle: 'Service not found',
    searchPlaceholder: 'Search service titles…',
    service: 'Service',
    features: 'Features',
    icon: 'Icon',
    iconHint: 'Shown next to the service on the website.',
    serviceTitle: 'Title',
    serviceDescription: 'Description',
    featuresHint: 'Short points shown under the service description. Type a feature and press Enter. Both lists may stay empty.',
    deleteTitle: 'Delete service',
    deleteMessage: (name) => `Delete the service “${name}”? This cannot be undone.`,
    emptyTitle: 'No services yet',
    emptyHint: 'Add the first service so it shows on the website.',
    activeLabel: 'Shown on the website',
    activeHint: 'A hidden service is not shown on the website nor offered on the contact form.',
    reorderIntro: 'Drag the services to change the order they appear in on the website. The order is saved automatically.',
    icons: {
      web: 'Web',
      mobile: 'Mobile',
      design: 'Design',
      erp: 'ERP',
      cloud: 'Cloud',
      ai: 'AI',
      support: 'Support',
    },
  },
}
