// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to this feature is here.
export default {
  ar: {
    title: 'فريقنا',
    description: 'أعضاء الفريق الذين تظهر بطاقاتهم في صفحة «فريقنا» على الموقع، وصفحة بروفايل خاصة بكل عضو.',
    new: 'عضو جديد',
    createTitle: 'إضافة عضو للفريق',
    editTitle: 'تعديل عضو الفريق',
    notFoundTitle: 'العضو غير موجود',
    searchPlaceholder: 'ابحث بالاسم أو المسمى الوظيفي…',
    member: 'العضو',
    jobTitle: 'المسمى الوظيفي',

    sectionPersonal: 'معلومات شخصية',
    sectionWork: 'معلومات العمل',
    sectionLinks: 'روابط التواصل',
    sectionStatus: 'الحالة والرابط',
    sectionAddress: 'رابط صفحتك',

    name: 'الاسم',
    avatar: 'الصورة الشخصية',
    bio: 'نبذة شخصية',
    email: 'البريد الإلكتروني',
    emailHint: 'اختياري، للاستخدام الداخلي فقط — لا يظهر في الموقع العام.',
    phone: 'رقم الهاتف',
    phoneHint: 'اختياري، للاستخدام الداخلي فقط — لا يظهر في الموقع العام.',
    location: 'الموقع الجغرافي',
    department: 'القسم',
    yearsExperience: 'سنوات الخبرة',

    cv: {
      skills: {
        title: 'المهارات',
        description: 'كل مهارة بعنوان ووصف قصير، وتظهر في عمودين في الصفحة الشخصية.',
        empty: 'لا توجد مهارات بعد.',
        add: 'إضافة مهارة',
        fields: { title: 'المهارة', description: 'الوصف' },
        placeholders: { title: { ar: 'تطوير Flutter', en: 'Flutter development' } },
      },
      experience: {
        title: 'الخبرات العملية',
        description: 'الوظائف والأعمال السابقة والحالية.',
        empty: 'لا توجد خبرات بعد.',
        add: 'إضافة خبرة',
        fields: { title: 'المسمى الوظيفي', company: 'جهة العمل', location: 'المكان', description: 'الوصف' },
        placeholders: { title: { ar: 'مطوّر Flutter', en: 'Flutter Developer' }, company: { ar: 'شركة X', en: 'Company X' }, location: { ar: 'دمشق، سوريا', en: 'Damascus, Syria' } },
      },
      education: {
        title: 'الدراسة',
        description: 'الشهادات الجامعية والدراسية مع تواريخها. فعّل «حاليًا» إذا كانت الدراسة مستمرة.',
        empty: 'لا توجد دراسة بعد.',
        add: 'إضافة دراسة',
        fields: { degree: 'الدرجة / التخصص', school: 'الجامعة / المدرسة', location: 'المكان', description: 'الوصف' },
        placeholders: { degree: { ar: 'بكالوريوس هندسة معلوماتية', en: "Bachelor's in IT Engineering" }, school: { ar: 'جامعة دمشق', en: 'Damascus University' }, location: { ar: 'دمشق، سوريا', en: 'Damascus, Syria' } },
      },
      certifications: {
        title: 'الشهادات',
        description: 'الشهادات والجوائز، مع رابط اختياري لكل منها.',
        empty: 'لا توجد شهادات بعد.',
        add: 'إضافة شهادة',
        fields: { title: 'الشهادة', description: 'معلومات إضافية' },
      },
      languages: {
        title: 'اللغات',
        description: 'اللغات التي يتقنها ومستواه في كل منها.',
        empty: 'لا توجد لغات بعد.',
        add: 'إضافة لغة',
        fields: { name: 'اللغة', level: 'المستوى' },
        placeholders: { name: { ar: 'الإنجليزية', en: 'English' }, level: { ar: 'متوسط (B1)', en: 'Intermediate (B1)' } },
      },
    },
    cvEntryN: (n) => `عنصر ${n}`,
    cvMoveUp: (label) => `نقل «${label}» للأعلى`,
    cvMoveDown: (label) => `نقل «${label}» للأسفل`,
    cvRemove: (label) => `حذف «${label}»`,
    cvStart: 'تاريخ البدء',
    cvEnd: 'تاريخ الانتهاء',
    cvCurrent: 'حاليًا',
    cvLink: 'رابط',

    linksDescription: 'أضف أي عدد من الروابط، بالترتيب الذي تريده أن يظهر.',
    linksEmpty: 'لا توجد روابط بعد.',
    linkAdd: 'إضافة رابط',
    linkPlatform: 'المنصة',
    linkUrl: 'الرابط',
    linkLabel: 'الاسم الظاهر',
    linkLabelHint: 'اسم الرابط كما يظهر في الموقع.',
    platforms: {
      linkedin: 'لينكد إن', github: 'جيت هاب', website: 'موقع شخصي', x: 'إكس (تويتر)', facebook: 'فيسبوك', instagram: 'إنستغرام',
      youtube: 'يوتيوب', behance: 'بيهانس', dribbble: 'دريبل', telegram: 'تيليغرام', whatsapp: 'واتساب', other: 'أخرى',
    },
    discard: 'تجاهل التغييرات',

    slug: 'الرابط (Slug)',
    slugHint: 'يظهر في رابط الصفحة: /team/الرابط. اتركه فارغًا لتوليده تلقائيًا من الاسم الإنجليزي.',
    activeLabel: 'فعّال',
    activeHint: 'الأعضاء غير الفعّالين لا يظهرون في صفحة «فريقنا» ولا صفحاتهم الشخصية على الموقع.',

    linkedAccount: 'الحساب المرتبط في لوحة التحكم',
    linkedAccountHint: 'اختياري. صاحب هذا الحساب يستطيع تعديل ملفه الشخصي ومشاريعه فقط من صفحة «بورتفوليو أعمالي»، دون الوصول لبقية الأعضاء أو لأي قسم آخر.',
    linkedAccountNone: '— بدون —',

    deleteTitle: 'حذف عضو الفريق',
    deleteMessage: (name) => `هل تريد حذف «${name}» من الفريق؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا يوجد أعضاء بعد',
    emptyHint: 'أضف أول عضو ليظهر في صفحة «فريقنا» على الموقع.',
    reorderIntro: 'اسحب الأعضاء لتغيير ترتيب ظهورهم في الموقع. يُحفظ الترتيب تلقائيًا.',

    portfolioTitle: 'المشاريع',
    portfolioDescription: 'المشاريع التي تظهر في الصفحة الشخصية على الموقع: عنوان ووصف وصورة، مع تفاصيل اختيارية كالتقنيات والتواريخ والرابط.',
    portfolioEmptyTitle: 'لا توجد مشاريع بعد',
    portfolioEmptyHint: 'أضف أول مشروع ليظهر في الصفحة الشخصية.',
    portfolioItemNew: 'مشروع جديد',
    portfolioItemEdit: 'تعديل المشروع',
    portfolioItemEditAction: (title) => `تعديل «${title}»`,
    portfolioItemDeleteAction: (title) => `حذف «${title}»`,
    portfolioItemDeleteTitle: 'حذف المشروع',
    portfolioItemDeleteMessage: (title) => `هل تريد حذف «${title}»؟ لا يمكن التراجع عن ذلك.`,
    portfolioItemTitle: 'عنوان المشروع',
    portfolioItemDescription: 'وصف المشروع',
    portfolioItemSubtitle: 'عنوان فرعي',
    portfolioItemSubtitleHint: 'اختياري، مثل التقنيات المستخدمة أو دورك في المشروع.',
    portfolioItemLink: 'رابط المشروع',
    portfolioItemLinkHint: 'اختياري. يظهر بجانب عنوان المشروع.',
    portfolioItemCover: 'الصورة الرئيسية',
    portfolioItemCoverHint: 'اختياري.',
    portfolioItemGallery: 'صور إضافية',
    portfolioItemGalleryHint: 'اختياري.',
    portfolioItemVideo: 'رابط فيديو',
    portfolioItemVideoHint: 'اختياري. رابط يوتيوب أو فيميو أو أي رابط فيديو مباشر.',

    myPortfolioTitle: 'بورتفوليو أعمالي',
  },
  en: {
    title: 'Our Team',
    description: 'The staff members shown as cards on the public "Our Team" page, each with their own portfolio page.',
    new: 'New member',
    createTitle: 'Add a team member',
    editTitle: 'Edit team member',
    notFoundTitle: 'Member not found',
    searchPlaceholder: 'Search by name or job title…',
    member: 'Member',
    jobTitle: 'Job title',

    sectionPersonal: 'Personal information',
    sectionWork: 'Work information',
    sectionLinks: 'Links',
    sectionStatus: 'Status & URL',
    sectionAddress: 'Your page URL',

    name: 'Name',
    avatar: 'Photo',
    bio: 'Bio',
    email: 'Email',
    emailHint: 'Optional, internal use only — never shown on the public site.',
    phone: 'Phone',
    phoneHint: 'Optional, internal use only — never shown on the public site.',
    location: 'Location',
    department: 'Department',
    yearsExperience: 'Years of experience',

    cv: {
      skills: {
        title: 'Skills',
        description: 'Each skill has a title and a short description; they are shown in two columns on the profile page.',
        empty: 'No skills yet.',
        add: 'Add skill',
        fields: { title: 'Skill', description: 'Description' },
        placeholders: { title: { ar: 'تطوير Flutter', en: 'Flutter development' } },
      },
      experience: {
        title: 'Work experience',
        description: 'Past and current jobs.',
        empty: 'No experience yet.',
        add: 'Add experience',
        fields: { title: 'Job title', company: 'Employer', location: 'Location', description: 'Description' },
        placeholders: { title: { ar: 'مطوّر Flutter', en: 'Flutter Developer' }, company: { ar: 'شركة X', en: 'Company X' }, location: { ar: 'دمشق، سوريا', en: 'Damascus, Syria' } },
      },
      education: {
        title: 'Education',
        description: 'Degrees and studies with their dates. Tick “Present” while still studying.',
        empty: 'No education yet.',
        add: 'Add education',
        fields: { degree: 'Degree / field', school: 'University / school', location: 'Location', description: 'Description' },
        placeholders: { degree: { ar: 'بكالوريوس هندسة معلوماتية', en: "Bachelor's in IT Engineering" }, school: { ar: 'جامعة دمشق', en: 'Damascus University' }, location: { ar: 'دمشق، سوريا', en: 'Damascus, Syria' } },
      },
      certifications: {
        title: 'Certificates',
        description: 'Certificates and awards, each with an optional link.',
        empty: 'No certificates yet.',
        add: 'Add certificate',
        fields: { title: 'Certificate', description: 'Additional information' },
      },
      languages: {
        title: 'Languages',
        description: 'Languages spoken and the level of each.',
        empty: 'No languages yet.',
        add: 'Add language',
        fields: { name: 'Language', level: 'Level' },
        placeholders: { name: { ar: 'الإنجليزية', en: 'English' }, level: { ar: 'متوسط (B1)', en: 'Intermediate (B1)' } },
      },
    },
    cvEntryN: (n) => `Entry ${n}`,
    cvMoveUp: (label) => `Move “${label}” up`,
    cvMoveDown: (label) => `Move “${label}” down`,
    cvRemove: (label) => `Remove “${label}”`,
    cvStart: 'Start date',
    cvEnd: 'End date',
    cvCurrent: 'Present',
    cvLink: 'Link',

    linksDescription: 'Add as many links as you like, in the order they should appear.',
    linksEmpty: 'No links yet.',
    linkAdd: 'Add link',
    linkPlatform: 'Platform',
    linkUrl: 'URL',
    linkLabel: 'Display name',
    linkLabelHint: 'The name shown for this link on the website.',
    platforms: {
      linkedin: 'LinkedIn', github: 'GitHub', website: 'Website', x: 'X (Twitter)', facebook: 'Facebook', instagram: 'Instagram',
      youtube: 'YouTube', behance: 'Behance', dribbble: 'Dribbble', telegram: 'Telegram', whatsapp: 'WhatsApp', other: 'Other',
    },
    discard: 'Discard changes',

    slug: 'Slug',
    slugHint: 'Used in the page URL: /team/slug. Leave blank to generate one from the English name.',
    activeLabel: 'Active',
    activeHint: 'Inactive members are hidden from the "Our Team" page and their own portfolio page.',

    linkedAccount: 'Linked dashboard account',
    linkedAccountHint: 'Optional. That account can edit only its own profile and projects from "My portfolio", with no access to other members or any other section.',
    linkedAccountNone: '— None —',

    deleteTitle: 'Delete team member',
    deleteMessage: (name) => `Delete “${name}” from the team? This cannot be undone.`,
    emptyTitle: 'No team members yet',
    emptyHint: 'Add the first member so they show up on the "Our Team" page.',
    reorderIntro: 'Drag the members to change the order they appear in on the website. The order is saved automatically.',

    portfolioTitle: 'Projects',
    portfolioDescription: 'The projects shown on the public profile page: a title, a description and an image, with optional details such as the stack, dates and a link.',
    portfolioEmptyTitle: 'No projects yet',
    portfolioEmptyHint: 'Add the first project so it shows up on the profile page.',
    portfolioItemNew: 'New project',
    portfolioItemEdit: 'Edit project',
    portfolioItemEditAction: (title) => `Edit "${title}"`,
    portfolioItemDeleteAction: (title) => `Delete "${title}"`,
    portfolioItemDeleteTitle: 'Delete project',
    portfolioItemDeleteMessage: (title) => `Delete "${title}"? This cannot be undone.`,
    portfolioItemTitle: 'Title',
    portfolioItemDescription: 'Description',
    portfolioItemSubtitle: 'Subtitle',
    portfolioItemSubtitleHint: 'Optional, e.g. the stack or your role in the project.',
    portfolioItemLink: 'Project link',
    portfolioItemLinkHint: 'Optional. Shown next to the project title.',
    portfolioItemCover: 'Cover image',
    portfolioItemCoverHint: 'Optional.',
    portfolioItemGallery: 'Additional images',
    portfolioItemGalleryHint: 'Optional.',
    portfolioItemVideo: 'Video URL',
    portfolioItemVideoHint: 'Optional. A YouTube, Vimeo or direct video link.',

    myPortfolioTitle: 'My Portfolio',
  },
}
