// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to this feature is here.
export default {
  ar: {
    title: 'فريقنا',
    description: 'أعضاء الفريق الذين تظهر بطاقاتهم في صفحة «فريقنا» على الموقع، وصفحة بروفايل خاصة بكل عضو.',
    new: 'عضو جديد',
    createTitle: 'إضافة عضو للفريق',
    editTitle: 'تعديل عضو الفريق',
    notFoundTitle: 'العضو غير موجود',
    searchPlaceholder: 'ابحث بالاسم أو المسمى الوظيفي…',
    member: 'العضو',
    jobTitle: 'المسمى الوظيفي',

    sectionPersonal: 'معلومات شخصية',
    sectionWork: 'معلومات العمل',
    sectionCv: 'السيرة الذاتية',
    sectionLinks: 'روابط التواصل',
    sectionStatus: 'الحالة والرابط',

    name: 'الاسم',
    avatar: 'الصورة الشخصية',
    bio: 'نبذة شخصية',
    email: 'البريد الإلكتروني',
    emailHint: 'اختياري، للاستخدام الداخلي فقط — لا يظهر في الموقع العام.',
    phone: 'رقم الهاتف',
    phoneHint: 'اختياري، للاستخدام الداخلي فقط — لا يظهر في الموقع العام.',
    location: 'الموقع الجغرافي',
    department: 'القسم',
    yearsExperience: 'سنوات الخبرة',

    skills: 'المهارات',
    skillsHint: 'اكتب المهارة ثم اضغط Enter لإضافتها.',
    education: 'المؤهلات العلمية',
    educationHint: 'كل سطر يمثل مؤهلاً، مثال: «بكالوريوس هندسة معلوماتية — جامعة دمشق، 2018».',
    experience: 'الخبرات العملية',
    experienceHint: 'كل سطر يمثل خبرة سابقة، مثال: «مطوّر واجهات أمامية — شركة X، 2019–2021».',
    certifications: 'الشهادات',
    languages: 'اللغات',

    linkedin: 'لينكد إن',
    github: 'جيت هاب',
    website: 'الموقع الشخصي',
    twitter: 'إكس (تويتر)',

    slug: 'الرابط (Slug)',
    slugHint: 'يظهر في رابط الصفحة: /team/الرابط. اتركه فارغًا لتوليده تلقائيًا من الاسم الإنجليزي.',
    activeLabel: 'فعّال',
    activeHint: 'الأعضاء غير الفعّالين لا يظهرون في صفحة «فريقنا» ولا صفحاتهم الشخصية على الموقع.',

    linkedAccount: 'الحساب المرتبط في لوحة التحكم',
    linkedAccountHint: 'اختياري. صاحب هذا الحساب يمكنه تعديل معرض أعماله الخاص فقط من صفحة «بورتفوليو أعمالي»، حتى بدون صلاحية «فريقنا».',
    linkedAccountNone: '— بدون —',

    deleteTitle: 'حذف عضو الفريق',
    deleteMessage: (name) => `هل تريد حذف «${name}» من الفريق؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا يوجد أعضاء بعد',
    emptyHint: 'أضف أول عضو ليظهر في صفحة «فريقنا» على الموقع.',
    reorderIntro: 'اسحب الأعضاء لتغيير ترتيب ظهورهم في الموقع. يُحفظ الترتيب تلقائيًا.',

    portfolioTitle: 'معرض الأعمال',
    portfolioDescription: 'مشاريع هذا الشخص التي تظهر في صفحته الشخصية على الموقع.',
    portfolioEmptyTitle: 'لا توجد أعمال بعد',
    portfolioEmptyHint: 'أضف أول عمل ليظهر في الصفحة الشخصية.',
    portfolioItemNew: 'عمل جديد',
    portfolioItemEdit: 'تعديل العمل',
    portfolioItemEditAction: (title) => `تعديل «${title}»`,
    portfolioItemDeleteAction: (title) => `حذف «${title}»`,
    portfolioItemDeleteTitle: 'حذف العمل',
    portfolioItemDeleteMessage: (title) => `هل تريد حذف «${title}»؟ لا يمكن التراجع عن ذلك.`,
    portfolioItemTitle: 'عنوان العمل',
    portfolioItemDescription: 'وصف العمل',
    portfolioItemCover: 'الصورة الرئيسية',
    portfolioItemCoverHint: 'اختياري.',
    portfolioItemGallery: 'صور إضافية',
    portfolioItemGalleryHint: 'اختياري.',
    portfolioItemVideo: 'رابط فيديو',
    portfolioItemVideoHint: 'اختياري. رابط يوتيوب أو فيميو أو أي رابط فيديو مباشر.',

    myPortfolioTitle: 'بورتفوليو أعمالي',
  },
  en: {
    title: 'Our Team',
    description: 'The staff members shown as cards on the public "Our Team" page, each with their own portfolio page.',
    new: 'New member',
    createTitle: 'Add a team member',
    editTitle: 'Edit team member',
    notFoundTitle: 'Member not found',
    searchPlaceholder: 'Search by name or job title…',
    member: 'Member',
    jobTitle: 'Job title',

    sectionPersonal: 'Personal information',
    sectionWork: 'Work information',
    sectionCv: 'CV',
    sectionLinks: 'Links',
    sectionStatus: 'Status & URL',

    name: 'Name',
    avatar: 'Photo',
    bio: 'Bio',
    email: 'Email',
    emailHint: 'Optional, internal use only — never shown on the public site.',
    phone: 'Phone',
    phoneHint: 'Optional, internal use only — never shown on the public site.',
    location: 'Location',
    department: 'Department',
    yearsExperience: 'Years of experience',

    skills: 'Skills',
    skillsHint: 'Type a skill and press Enter to add it.',
    education: 'Education',
    educationHint: 'One entry per line, e.g. "BSc in Software Engineering — Damascus University, 2018".',
    experience: 'Work experience',
    experienceHint: 'One entry per line, e.g. "Frontend Developer — Company X, 2019–2021".',
    certifications: 'Certifications',
    languages: 'Languages',

    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Personal website',
    twitter: 'X (Twitter)',

    slug: 'Slug',
    slugHint: 'Used in the page URL: /team/slug. Leave blank to generate one from the English name.',
    activeLabel: 'Active',
    activeHint: 'Inactive members are hidden from the "Our Team" page and their own portfolio page.',

    linkedAccount: 'Linked dashboard account',
    linkedAccountHint: 'Optional. That account can edit only its own portfolio from "My portfolio", even without the "Our Team" permission.',
    linkedAccountNone: '— None —',

    deleteTitle: 'Delete team member',
    deleteMessage: (name) => `Delete “${name}” from the team? This cannot be undone.`,
    emptyTitle: 'No team members yet',
    emptyHint: 'Add the first member so they show up on the "Our Team" page.',
    reorderIntro: 'Drag the members to change the order they appear in on the website. The order is saved automatically.',

    portfolioTitle: 'Portfolio',
    portfolioDescription: "This person's projects, shown on their public profile page.",
    portfolioEmptyTitle: 'No portfolio items yet',
    portfolioEmptyHint: 'Add the first item so it shows up on the profile page.',
    portfolioItemNew: 'New item',
    portfolioItemEdit: 'Edit item',
    portfolioItemEditAction: (title) => `Edit "${title}"`,
    portfolioItemDeleteAction: (title) => `Delete "${title}"`,
    portfolioItemDeleteTitle: 'Delete item',
    portfolioItemDeleteMessage: (title) => `Delete "${title}"? This cannot be undone.`,
    portfolioItemTitle: 'Title',
    portfolioItemDescription: 'Description',
    portfolioItemCover: 'Cover image',
    portfolioItemCoverHint: 'Optional.',
    portfolioItemGallery: 'Additional images',
    portfolioItemGalleryHint: 'Optional.',
    portfolioItemVideo: 'Video URL',
    portfolioItemVideoHint: 'Optional. A YouTube, Vimeo or direct video link.',

    myPortfolioTitle: 'My Portfolio',
  },
}
