// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to this feature is here.
const arStars = (n) => (n === 1 ? 'نجمة واحدة' : n === 2 ? 'نجمتان' : `${n} نجوم`)

export default {
  ar: {
    title: 'آراء العملاء',
    description: 'آراء العملاء وتقييماتهم التي تظهر في الموقع.',
    new: 'رأي جديد',
    createTitle: 'إضافة رأي عميل',
    editTitle: 'تعديل رأي العميل',
    notFoundTitle: 'الرأي غير موجود',
    searchPlaceholder: 'ابحث بالاسم أو الشركة أو نص الرأي…',
    client: 'العميل',
    company: 'الشركة',
    companyHint: 'اختيارية، تظهر بجانب اسم العميل.',
    quote: 'نص الرأي',
    name: 'الاسم',
    avatar: 'الصورة الشخصية',
    avatarHint: 'اختيارية، تظهر بجانب الرأي في الموقع.',
    rating: 'التقييم',
    ratingOption: arStars,
    ratingOf: (n) => `${arStars(n)} من 5`,
    activeLabel: 'فعّال',
    activeHint: 'الآراء غير الفعّالة لا تظهر في الموقع.',
    deleteTitle: 'حذف الرأي',
    deleteMessage: (name) => `هل تريد حذف رأي «${name}»؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا توجد آراء بعد',
    emptyHint: 'أضف أول رأي لعميل ليظهر في الموقع.',
    reorderIntro: 'اسحب الآراء لتغيير ترتيب ظهورها في الموقع. يُحفظ الترتيب تلقائيًا.',
  },
  en: {
    title: 'Testimonials',
    description: 'The client quotes and ratings shown on the website.',
    new: 'New testimonial',
    createTitle: 'Add a testimonial',
    editTitle: 'Edit testimonial',
    notFoundTitle: 'Testimonial not found',
    searchPlaceholder: 'Search by name, company or quote…',
    client: 'Client',
    company: 'Company',
    companyHint: 'Optional, shown next to the client’s name.',
    quote: 'Quote',
    name: 'Name',
    avatar: 'Photo',
    avatarHint: 'Optional, shown next to the quote on the website.',
    rating: 'Rating',
    ratingOption: (n) => (n === 1 ? '1 star' : `${n} stars`),
    ratingOf: (n) => `${n} out of 5 stars`,
    activeLabel: 'Active',
    activeHint: 'Inactive testimonials are not shown on the website.',
    deleteTitle: 'Delete testimonial',
    deleteMessage: (name) => `Delete the testimonial from “${name}”? This cannot be undone.`,
    emptyTitle: 'No testimonials yet',
    emptyHint: 'Add the first client testimonial so it shows on the website.',
    reorderIntro: 'Drag the testimonials to change the order they appear in on the website. The order is saved automatically.',
  },
}
