// Feature strings: { ar: {…}, en: {…} }. Generic words (save, cancel, delete, validation messages…) come from `useCommon()`.
export default {
  ar: {
    accountTitle: 'حسابي',
    accountDescription: 'حدّث بياناتك الشخصية وغيّر كلمة المرور.',
    backToUsers: 'المستخدمون',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    profileTitle: 'البيانات الشخصية',
    profileDescription: 'الاسم والبريد الإلكتروني الذي تدخل به إلى لوحة التحكم.',
    profileSaved: 'تم تحديث بياناتك',
    passwordTitle: 'تغيير كلمة المرور',
    passwordDescription: 'بعد التغيير تبقى جلستك الحالية مفتوحة ويتم تسجيل خروجك من الأجهزة الأخرى.',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    passwordHintCreate: 'ثمانية أحرف على الأقل.',
    passwordsMismatch: 'كلمتا المرور غير متطابقتين',
    currentPasswordWrong: 'كلمة المرور الحالية غير صحيحة.',
    changePassword: 'تغيير كلمة المرور',
    passwordChanged: 'تم تغيير كلمة المرور، وتم تسجيل خروجك من الأجهزة الأخرى.',
    showPassword: 'إظهار كلمة المرور',
    hidePassword: 'إخفاء كلمة المرور',
  },
  en: {
    accountTitle: 'My account',
    accountDescription: 'Update your details and change your password.',
    backToUsers: 'Users',
    name: 'Name',
    email: 'Email',
    profileTitle: 'Profile',
    profileDescription: 'The name and email you use to sign in to the dashboard.',
    profileSaved: 'Your details were updated',
    passwordTitle: 'Change password',
    passwordDescription: 'Your current session stays open; you are signed out of your other devices.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordHintCreate: 'At least 8 characters.',
    passwordsMismatch: 'The two passwords do not match',
    currentPasswordWrong: 'The current password is incorrect.',
    changePassword: 'Change password',
    passwordChanged: 'Password changed. You were signed out of your other devices.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
}
