// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only add what is specific to this feature.
export default {
  ar: {
    title: 'الأسئلة الشائعة',
    description: 'الأسئلة والأجوبة التي تظهر في قسم الأسئلة الشائعة في الموقع.',
    new: 'سؤال جديد',
    createTitle: 'إضافة سؤال',
    editTitle: 'تعديل السؤال',
    question: 'السؤال',
    answer: 'الإجابة',
    searchPlaceholder: 'ابحث في الأسئلة والأجوبة…',
    activeLabel: 'فعّال',
    activeHint: 'الأسئلة غير الفعّالة لا تظهر في الموقع.',
    deleteTitle: 'حذف السؤال',
    deleteMessage: (question) => `هل تريد حذف السؤال «${question}»؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا توجد أسئلة بعد',
    emptyHint: 'أضف أول سؤال ليظهر في الموقع.',
    notFoundTitle: 'السؤال غير موجود',
    reorderIntro: 'اسحب الأسئلة لتغيير ترتيب ظهورها في الموقع. يُحفظ الترتيب تلقائيًا.',
  },
  en: {
    title: 'FAQ',
    description: 'The questions and answers shown in the FAQ section of the website.',
    new: 'New question',
    createTitle: 'Add a question',
    editTitle: 'Edit question',
    question: 'Question',
    answer: 'Answer',
    searchPlaceholder: 'Search questions and answers…',
    activeLabel: 'Active',
    activeHint: 'Inactive questions are not shown on the website.',
    deleteTitle: 'Delete question',
    deleteMessage: (question) => `Delete the question “${question}”? This cannot be undone.`,
    emptyTitle: 'No questions yet',
    emptyHint: 'Add the first question so it shows on the website.',
    notFoundTitle: 'Question not found',
    reorderIntro: 'Drag the questions to change the order they appear in on the website. The order is saved automatically.',
  },
}
