// Feature strings. The status names (New / In progress / Done) come from the common strings (`c.statusLabels`).
const arCount = (n) => (n === 1 ? 'طلب واحد' : n === 2 ? 'طلبين' : n <= 10 ? `${n} طلبات` : `${n} طلبًا`)
const enCount = (n) => `${n} ${n === 1 ? 'request' : 'requests'}`

export default {
  ar: {
    title: 'طلبات العروض',
    description: 'طلبات الحجز والاستفسارات الواردة من صفحات العروض في الموقع، منفصلة عن رسائل «تواصل معنا».',
    searchPlaceholder: 'ابحث بالاسم أو الهاتف أو العرض…',
    statusTabs: 'تصفية الطلبات حسب الحالة',
    typeFilter: 'نوع الطلب',
    types: { booking: 'حجز', inquiry: 'استفسار' },
    allTypes: 'كل الأنواع',

    offer: 'العرض',
    plan: 'الباقة',
    type: 'النوع',
    name: 'الاسم',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    receivedAt: 'تاريخ الاستلام',
    view: 'عرض الطلب',
    statusOf: (name) => `حالة طلب ${name}`,
    offerDeleted: 'عرض محذوف',

    bulkActions: 'إجراءات على الطلبات المحددة',
    markAs: { new: 'تعيين كجديد', in_progress: 'تعيين كقيد المعالجة', done: 'تعيين كتمت' },
    clearSelection: 'إلغاء التحديد',
    deleteTitle: 'حذف الطلب',
    deleteMessage: (name) => `هل تريد حذف طلب «${name}»؟ لا يمكن التراجع عن ذلك.`,
    bulkDeleteTitle: 'حذف الطلبات المحددة',
    bulkDeleteMessage: (n) => `سيتم حذف ${arCount(n)} نهائيًا. لا يمكن التراجع عن ذلك.`,

    emptyTitle: 'لا توجد طلبات عروض بعد',
    emptyHint: 'ستظهر هنا طلبات الحجز والاستفسارات التي يرسلها الزوار من صفحات العروض.',
    notFoundTitle: 'الطلب غير موجود',

    messageTitle: { booking: 'ملاحظة الحجز', inquiry: 'السؤال' },
    noMessage: 'لم يكتب الزائر ملاحظة.',
    detailsTitle: 'بيانات الطلب',
    statusHint: 'يُحفظ تغيير الحالة فورًا.',
    notesTitle: 'ملاحظات داخلية',
    notesHint: 'لا يراها الزائر، وهي للفريق فقط.',
    notesPlaceholder: 'مثال: تم التواصل وتفعيل الاشتراك الشهري…',
    saveNotes: 'حفظ الملاحظات',
    call: 'اتصال',
    whatsapp: 'واتساب',
    notProvided: 'غير مذكور',

    subscriptionTitle: 'الاشتراك',
    subscriptionHint: 'مدة الاشتراك بالأيام (تُنسخ من الباقة المختارة ويمكن تعديلها) وتاريخ قبول الطلب؛ منهما يُحسب تاريخ الانتهاء.',
    durationDays: 'مدة الاشتراك',
    durationDaysHint: 'بالأيام.',
    days: 'يوم',
    durationLess: 'إنقاص يوم',
    durationMore: 'زيادة يوم',
    acceptedAt: 'تاريخ قبول الطلب',
    acceptToday: 'قبول الطلب اليوم',
    expiresAt: 'تاريخ الانتهاء',
    expiresUnknown: 'يُحسب بعد تحديد المدة وتاريخ القبول',
    notAccepted: 'لم يُقبل بعد',
    daysLeft: (n) => (n === 1 ? 'متبقٍ يوم واحد' : n === 2 ? 'متبقٍ يومان' : n <= 10 ? `متبقٍ ${n} أيام` : `متبقٍ ${n} يومًا`),
    endsToday: 'ينتهي اليوم',
    endedAgo: (n) => (n === 1 ? 'انتهى منذ يوم' : n === 2 ? 'انتهى منذ يومين' : n <= 10 ? `انتهى منذ ${n} أيام` : `انتهى منذ ${n} يومًا`),
    saveSubscription: 'حفظ الاشتراك',
  },
  en: {
    title: 'Offer requests',
    description: 'Bookings and inquiries sent from the offers pages on the website, kept apart from the contact-form messages.',
    searchPlaceholder: 'Search by name, phone or offer…',
    statusTabs: 'Filter requests by status',
    typeFilter: 'Request type',
    types: { booking: 'Booking', inquiry: 'Inquiry' },
    allTypes: 'All types',

    offer: 'Offer',
    plan: 'Plan',
    type: 'Type',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    receivedAt: 'Received',
    view: 'View request',
    statusOf: (name) => `Status of ${name}`,
    offerDeleted: 'Deleted offer',

    bulkActions: 'Actions for the selected requests',
    markAs: { new: 'Mark as new', in_progress: 'Mark as in progress', done: 'Mark as done' },
    clearSelection: 'Clear selection',
    deleteTitle: 'Delete request',
    deleteMessage: (name) => `Delete the request from “${name}”? This cannot be undone.`,
    bulkDeleteTitle: 'Delete selected requests',
    bulkDeleteMessage: (n) => `${enCount(n)} will be permanently deleted. This cannot be undone.`,

    emptyTitle: 'No offer requests yet',
    emptyHint: 'Bookings and inquiries sent from the offers pages will show up here.',
    notFoundTitle: 'Request not found',

    messageTitle: { booking: 'Booking note', inquiry: 'Question' },
    noMessage: 'The visitor did not leave a note.',
    detailsTitle: 'Request details',
    statusHint: 'A status change is saved immediately.',
    notesTitle: 'Internal notes',
    notesHint: 'Visitors never see these. They are for the team only.',
    notesPlaceholder: 'e.g. Called back and activated the monthly plan…',
    saveNotes: 'Save notes',
    call: 'Call',
    whatsapp: 'WhatsApp',
    notProvided: 'Not provided',

    subscriptionTitle: 'Subscription',
    subscriptionHint: 'Its length in days (copied from the chosen plan, adjustable) and the day the request was accepted; the end date follows from both.',
    durationDays: 'Subscription length',
    durationDaysHint: 'In days.',
    days: 'days',
    durationLess: 'One day less',
    durationMore: 'One day more',
    acceptedAt: 'Accepted on',
    acceptToday: 'Accept today',
    expiresAt: 'Ends on',
    expiresUnknown: 'Set once the length and the acceptance day are known',
    notAccepted: 'Not accepted yet',
    daysLeft: (n) => `${n} ${n === 1 ? 'day' : 'days'} left`,
    endsToday: 'Ends today',
    endedAgo: (n) => `Ended ${n} ${n === 1 ? 'day' : 'days'} ago`,
    saveSubscription: 'Save subscription',
  },
}
