// Feature strings: { ar: {…}, en: {…} }. Generic words (save, cancel, delete, "Active"…) come from `useCommon()`.
export default {
  ar: {
    title: 'العروض',
    description: 'المنتجات والخدمات التي تعرضها الشركة باشتراك (تطبيق محاسبة، خدمة سحابية…)، وتظهر في صفحة «العروض» على الموقع.',
    new: 'عرض جديد',
    createTitle: 'إضافة عرض',
    editTitle: 'تعديل العرض',
    notFoundTitle: 'العرض غير موجود',
    searchPlaceholder: 'ابحث في العروض…',
    offer: 'العرض',
    plansCount: 'الباقات',
    deleteTitle: 'حذف العرض',
    deleteMessage: (name) => `هل تريد حذف العرض «${name}»؟ طلباته تبقى في «طلبات العروض». لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا توجد عروض بعد',
    emptyHint: 'أضف أول عرض ليظهر في صفحة «العروض» على الموقع.',
    reorderIntro: 'اسحب العروض لتغيير ترتيب ظهورها في الموقع. يُحفظ الترتيب تلقائيًا.',

    sectionCard: 'بطاقة العرض',
    sectionCardHint: 'ما يظهر في صفحة العروض: الصورة والعنوان والوصف المختصر.',
    offerTitle: 'العنوان',
    short: 'وصف مختصر',
    shortHint: 'سطر أو سطران يظهران على البطاقة.',
    cover: 'صورة البطاقة',
    coverHint: 'تظهر على البطاقة وفي أعلى صفحة العرض.',

    sectionDetails: 'تفاصيل العرض',
    sectionDetailsHint: 'تظهر في صفحة العرض: شرح كامل وصور وفيديو.',
    fullDescription: 'الشرح الكامل',
    gallery: 'صور إضافية',
    galleryHint: 'لقطات من التطبيق أو الخدمة. تُكبَّر عند الضغط عليها.',
    video: 'رابط فيديو شرح',
    videoHint: 'اختياري. رابط يوتيوب أو فيميو أو أي رابط فيديو مباشر.',

    features: 'الميزات',
    featuresHint: 'ما يقدمه العرض، ميزة بعد ميزة.',
    featuresEmpty: 'لا توجد ميزات بعد.',
    featureAdd: 'إضافة ميزة',
    featureTitle: 'الميزة',
    featureDescription: 'شرح الميزة',

    plans: 'باقات الاشتراك',
    plansHint: 'كل باقة باسم وسعر ووصف. يمكن للزائر اختيار باقة عند الحجز.',
    plansEmpty: 'لا توجد باقات بعد.',
    planAdd: 'إضافة باقة',
    planName: 'اسم الباقة',
    planPrice: 'السعر',
    planPriceHint: 'نص حر، مثل «20$» أو «مجانًا» أو «حسب الطلب».',
    planDuration: 'مدة الاشتراك',
    planDurationHint: 'عدد أيام الاشتراك. منه يُحسب تاريخ انتهاء الطلب بعد قبوله.',
    days: 'يوم',
    durationLess: 'إنقاص يوم',
    durationMore: 'زيادة يوم',
    durationPreset: { 30: 'شهر', 90: '3 أشهر', 180: '6 أشهر', 365: 'سنة' },
    planDescription: 'ما تتضمنه الباقة',
    planHighlighted: 'الباقة المميزة',
    planHighlightedHint: 'تظهر بإطار مميز على أنها الأكثر طلبًا.',
    plansNote: 'شرح نظام الاشتراك',
    plansNoteHint: 'اختياري. يظهر تحت الباقات، مثل طريقة الدفع والتجديد والإلغاء.',

    entryN: (n) => `عنصر ${n}`,
    moveUp: (label) => `نقل «${label}» للأعلى`,
    moveDown: (label) => `نقل «${label}» للأسفل`,
    remove: (label) => `حذف «${label}»`,

    sectionStatus: 'الحالة والرابط',
    slug: 'الرابط (Slug)',
    slugHint: 'يظهر في رابط الصفحة: /offers/الرابط. اتركه فارغًا لتوليده تلقائيًا من العنوان الإنجليزي.',
    activeLabel: 'ظاهر في الموقع',
    activeHint: 'العروض المخفية لا تظهر في صفحة العروض ولا يمكن الحجز عليها.',
  },
  en: {
    title: 'Offers',
    description: 'The products and services the company sells by subscription (an accounting app, a cloud service…), shown on the website "Offers" page.',
    new: 'New offer',
    createTitle: 'Add an offer',
    editTitle: 'Edit offer',
    notFoundTitle: 'Offer not found',
    searchPlaceholder: 'Search offers…',
    offer: 'Offer',
    plansCount: 'Plans',
    deleteTitle: 'Delete offer',
    deleteMessage: (name) => `Delete the offer “${name}”? Its requests stay in "Offer requests". This cannot be undone.`,
    emptyTitle: 'No offers yet',
    emptyHint: 'Add the first offer so it shows up on the "Offers" page.',
    reorderIntro: 'Drag the offers to change the order they appear in on the website. The order is saved automatically.',

    sectionCard: 'Offer card',
    sectionCardHint: 'What the Offers page shows: the image, the title and a short description.',
    offerTitle: 'Title',
    short: 'Short description',
    shortHint: 'One or two lines shown on the card.',
    cover: 'Card image',
    coverHint: 'Shown on the card and at the top of the offer page.',

    sectionDetails: 'Offer details',
    sectionDetailsHint: 'Shown on the offer page: the full explanation, images and a video.',
    fullDescription: 'Full description',
    gallery: 'Additional images',
    galleryHint: 'Screenshots of the app or service. They open larger when clicked.',
    video: 'Explainer video URL',
    videoHint: 'Optional. A YouTube, Vimeo or direct video link.',

    features: 'Features',
    featuresHint: 'What the offer provides, one feature at a time.',
    featuresEmpty: 'No features yet.',
    featureAdd: 'Add feature',
    featureTitle: 'Feature',
    featureDescription: 'Feature description',

    plans: 'Subscription plans',
    plansHint: 'Each plan has a name, a price and a description. Visitors can pick a plan when booking.',
    plansEmpty: 'No plans yet.',
    planAdd: 'Add plan',
    planName: 'Plan name',
    planPrice: 'Price',
    planPriceHint: 'Free text, e.g. “$20”, “Free” or “On request”.',
    planDuration: 'Subscription length',
    planDurationHint: 'How many days one subscription runs. A request’s end date is counted from it once accepted.',
    days: 'days',
    durationLess: 'One day less',
    durationMore: 'One day more',
    durationPreset: { 30: 'Month', 90: '3 months', 180: '6 months', 365: 'Year' },
    planDescription: 'What the plan includes',
    planHighlighted: 'Highlighted plan',
    planHighlightedHint: 'Shown with a distinct frame as the most popular one.',
    plansNote: 'How the subscription works',
    plansNoteHint: 'Optional. Shown under the plans: payment, renewal, cancellation…',

    entryN: (n) => `Entry ${n}`,
    moveUp: (label) => `Move “${label}” up`,
    moveDown: (label) => `Move “${label}” down`,
    remove: (label) => `Remove “${label}”`,

    sectionStatus: 'Status & URL',
    slug: 'Slug',
    slugHint: 'Used in the page URL: /offers/slug. Leave blank to generate one from the English title.',
    activeLabel: 'Shown on the website',
    activeHint: 'Hidden offers are left off the Offers page and cannot be booked.',
  },
}
