// Feature strings: { ar: {…}, en: {…} } read with `const t = useStrings(strings)`. Generic words (save, cancel,
// delete, "Active"…) come from `useCommon()` — only what is specific to this feature is here.
export default {
  ar: {
    title: 'الإحصائيات',
    description: 'الأرقام التي تظهر في الصفحة الرئيسية للموقع، مثل عدد المشاريع المنجزة وسنوات الخبرة.',
    new: 'إحصائية جديدة',
    createTitle: 'إضافة إحصائية',
    editTitle: 'تعديل الإحصائية',
    notFoundTitle: 'الإحصائية غير موجودة',
    searchPlaceholder: 'ابحث في القيم والتسميات…',
    value: 'القيمة',
    valueHint: 'نص قصير يظهر بخط كبير، مثل 240+ أو 98% (حتى 20 حرفًا).',
    label: 'التسمية',
    labelHint: 'تظهر أسفل الرقم، مثل «مشروع منجز».',
    deleteTitle: 'حذف الإحصائية',
    deleteMessage: (name) => `هل تريد حذف الإحصائية «${name}»؟ لا يمكن التراجع عن ذلك.`,
    emptyTitle: 'لا توجد إحصائيات بعد',
    emptyHint: 'أضف أول إحصائية لتظهر في الصفحة الرئيسية.',
    reorderIntro: 'اسحب الإحصائيات لتغيير ترتيب ظهورها في الموقع. يُحفظ الترتيب تلقائيًا.',
  },
  en: {
    title: 'Stats',
    description: 'The numbers shown on the home page of the website, such as projects delivered or years of experience.',
    new: 'New stat',
    createTitle: 'Add a stat',
    editTitle: 'Edit stat',
    notFoundTitle: 'Stat not found',
    searchPlaceholder: 'Search values and labels…',
    value: 'Value',
    valueHint: 'A short text shown in large type, such as 240+ or 98% (up to 20 characters).',
    label: 'Label',
    labelHint: 'Shown under the number, for example “Projects delivered”.',
    deleteTitle: 'Delete stat',
    deleteMessage: (name) => `Delete the stat “${name}”? This cannot be undone.`,
    emptyTitle: 'No stats yet',
    emptyHint: 'Add the first stat so it shows on the home page.',
    reorderIntro: 'Drag the stats to change the order they appear in on the website. The order is saved automatically.',
  },
}
